export enum Constant {
  BASE_URL = 'https://docbaodoithuong.com/user',
  BASE_URL_REWARD = 'https://docbaodoithuong.com/reward',
  SHARED_PREFERENCES_USER_KEY = 'USER_INFO',
  SHARED_PREFERENCES_TURN_KEY = 'USER_COIN',
  ATTENDANCE = 'ATTENDANCE',
  DAY_ACTIVE = 'DAY_ACTIVE',
  DAY_CHECK = 'DAY_CHECK',
  STEP = 'STEP',
  COIN = 'COIN',
  SKU = 'com.stptrkertts.steptrackertatasu',
  TOKEN = 'TOKEN',
  HOME_LINK_VI = 'https://www.ktien.vn/trangchutatasu',
  HOME_LINK_EN = 'https://www.ktien.vn/trangchutatasuen',
  HEALTH_LINK_VI = 'https://www.ktien.vn/mucsuckhoetatasu',
  HEALTH_LINK_EN = 'https://www.ktien.vn/mucsuckhoetatasuen',
  COMMUNITY_LINK_VI = 'https://www.ktien.vn/muccongdongtatasu',
  COMMUNITY_LINK_EN = 'https://www.ktien.vn/muccongdongtatasuen',
  PRACTICE_LINK_VI = 'https://www.ktien.vn/mucluyentaptatasu',
  PRACTICE_LINK_EN = 'https://www.ktien.vn/mucluyentaptatasuen',
  PROFILE_LINK_VI = 'https://www.ktien.vn/muccanhantatasu',
  PROFILE_LINK_EN = 'https://www.ktien.vn/muccanhantatasuen',
  BALEN_LINK_VI = 'https://www.ktien.vn/ruttienapptatasu',
  BALEN_LINK_EN = 'https://www.ktien.vn/ruttienapptatasuen',

  BASE_URL_IP = 'http://ip-api.com/',
}
